In [2]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google-play-scraper-1.0.2.tar.gz (52 kB)
     |████████████████████████████████| 52 kB 1.1 MB/s eta 0:00:011
Building wheels for collected packages: google-play-scraper
  Building wheel for google-play-scraper (setup.py) ... done
  Created wheel for google-play-scraper: filename=google_play_scraper-1.0.2-py3-none-any.whl size=24393 sha256=fce5925cf1b8d1cb2414b2886407a6c1efd8ffba7edfdf3b8539fadc62e24909
  Stored in directory: /root/.cache/pip/wheels/98/99/eb/bbb9d24a5c526980647efc10336eaaeffcf07749f581111128
Successfully built google-play-scraper
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.0.2

In [3]:
from google_play_scraper import app

import pandas as pd

import numpy as np

In [4]:
#Scrape desired number of reviews

from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'com.bibit.bibitid',
    lang='id', # defaults to 'en'
    country='id', 
    sort=Sort.NEWEST, # defaults to Sort.MOST_RELEVANT you can use Sort.NEWEST to get newst reviews
    count=5000, # defaults to 100
    filter_score_with=None # defaults to None(means all score) Use 1 or 2 or 3 or 4 or 5 to select certain score
)

In [5]:
df_busu = pd.DataFrame(np.array(result),columns=['review'])

df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))

df_busu.head()

                                            reviewId  ... repliedAt
0  gp:AOqpTOG2n09KItE89oMdi22O1vpJaLihcFNuQE1qWkK...  ...       NaT
1  gp:AOqpTOGeU9kqL7vFBh2C2HVIP_QoEn_ayBUpOwf4VZg...  ...       NaT
2  gp:AOqpTOH5inCPQuCCXDK8htnZ10SrNgxHDEKgN_LbP47...  ...       NaT
3  gp:AOqpTOHHd1BADcKvrZebY06b8QC6SPJJdGda-xHo4df...  ...       NaT
4  gp:AOqpTOE9Yhou3G57m0yKqX4yQqfGplUtDfXraYOnWen...  ...       NaT

[5 rows x 10 columns]

In [6]:
len(df_busu.index) #count the number of data we got

5000

In [7]:
df_busu[['userName', 'score','at', 'content']].head()  #preview userName, rating, date-time, and reviews only

                     userName  ...                                            content
0                Ahs Official  ...  Yang tidak saya sukai dari aplikasi ini, prose...
1  choirunnisaqorry indriyani  ...  Saya narik uang kok ga masuk2 rekening saya. P...
2             Wantok Dulmuluk  ...          Bibit memang benar benar mewujudkan mimpi
3              Rahmat Suharjo  ...  Gunakan reffcode undangan== masterku*: bonus c...
4         Yudiramadhan Herman  ...  zres5a6 yuk daftar pake refferal aku nanti aku...

[5 rows x 4 columns]

In [8]:
#Run This Code to Sort the Data By Date 

new_df = df_busu[['userName', 'score','at', 'content']]
sorted_df = new_df.sort_values(by='at', ascending=False) #Sort by Newst, change to True if you want to sort by Oldest.
sorted_df.head()

                     userName  ...                                            content
0                Ahs Official  ...  Yang tidak saya sukai dari aplikasi ini, prose...
1  choirunnisaqorry indriyani  ...  Saya narik uang kok ga masuk2 rekening saya. P...
2             Wantok Dulmuluk  ...          Bibit memang benar benar mewujudkan mimpi
3              Rahmat Suharjo  ...  Gunakan reffcode undangan== masterku*: bonus c...
4         Yudiramadhan Herman  ...  zres5a6 yuk daftar pake refferal aku nanti aku...

[5 rows x 4 columns]

In [9]:
my_df = sorted_df[['userName', 'score','at', 'content']] #get userName, rating, date-time, and reviews only

In [10]:
my_df.head()

                     userName  ...                                            content
0                Ahs Official  ...  Yang tidak saya sukai dari aplikasi ini, prose...
1  choirunnisaqorry indriyani  ...  Saya narik uang kok ga masuk2 rekening saya. P...
2             Wantok Dulmuluk  ...          Bibit memang benar benar mewujudkan mimpi
3              Rahmat Suharjo  ...  Gunakan reffcode undangan== masterku*: bonus c...
4         Yudiramadhan Herman  ...  zres5a6 yuk daftar pake refferal aku nanti aku...

[5 rows x 4 columns]

In [11]:
my_df.to_csv("bibit_scarper4.csv", index = False)  #Save the file as CSV , to download: click the folder icon on the left. the csv file should be there.