In [1]:
import pandas as pd
from textblob import TextBlob

In [2]:
columns = ["comment_english"]
df = pd.read_excel(r'C:\Users\Hp\TUGAS AKHIR 2\FACEBOOK_INDIHOME\data bersih_translate facebook indihome\databersih_english_facebook_indihome_2.xlsx', usecols=columns)
df['label_awal'] = ''
for i,x in df.comment_english.iteritems():
    label_awal = TextBlob(x)
    df['label_awal'][i] = label_awal.sentiment.polarity
    print("Index: ", i ,  "label_awal" , label_awal.sentiment.polarity)

Index:  0 label_awal -0.31666666666666665
Index:  1 label_awal -0.25
Index:  2 label_awal 0.0
Index:  3 label_awal 0.0
Index:  4 label_awal 0.0
Index:  5 label_awal 0.0
Index:  6 label_awal 0.44999999999999996
Index:  7 label_awal 0.18333333333333335
Index:  8 label_awal 0.44999999999999996
Index:  9 label_awal 0.06818181818181818
Index:  10 label_awal 0.0
Index:  11 label_awal -0.025000000000000022
Index:  12 label_awal 0.4
Index:  13 label_awal 0.2
Index:  14 label_awal 0.18333333333333335
Index:  15 label_awal 0.3
Index:  16 label_awal 0.0
Index:  17 label_awal 0.2
Index:  18 label_awal 0.0
Index:  19 label_awal 0.2
Index:  20 label_awal -0.15000000000000002
Index:  21 label_awal 0.39999999999999997
Index:  22 label_awal -0.1361904761904762
Index:  23 label_awal -0.15555555555555559
Index:  24 label_awal 0.7
Index:  25 label_awal -0.5
Index:  26 label_awal 0.13333333333333333
Index:  27 label_awal -0.6666666666666666
Index:  28 label_awal 0.2
Index:  29 label_awal 0.0
Index:  30 label_awal -0.75
Index:  31 label_awal -0.5
Index:  32 label_awal 0.0
Index:  33 label_awal -0.25
Index:  34 label_awal -0.06999999999999999
Index:  35 label_awal 0.2916666666666667
Index:  36 label_awal 0.425
Index:  37 label_awal 0.0
Index:  38 label_awal 0.0
Index:  39 label_awal 0.0
Index:  40 label_awal -0.07777777777777779
Index:  41 label_awal 0.0
Index:  42 label_awal 0.0
Index:  43 label_awal 0.0
Index:  44 label_awal 0.0
Index:  45 label_awal 0.0
Index:  46 label_awal 0.0
Index:  47 label_awal 0.5
Index:  48 label_awal 0.43333333333333335
Index:  49 label_awal 0.0
Index:  50 label_awal 0.0
Index:  51 label_awal -0.027777777777777773
Index:  52 label_awal 0.0
Index:  53 label_awal 0.0
Index:  54 label_awal -0.05
Index:  55 label_awal 0.11666666666666665
Index:  56 label_awal 0.43333333333333335
Index:  57 label_awal 0.30000000000000004
Index:  58 label_awal -0.25
Index:  59 label_awal 0.1
Index:  60 label_awal 0.44999999999999996
Index:  61 label_awal 0.375
Index:  62 label_awal 0.0
Index:  63 label_awal 0.6
Index:  64 label_awal 0.0
Index:  65 label_awal 0.0
Index:  66 label_awal 0.0
Index:  67 label_awal 0.0
Index:  68 label_awal 0.0
Index:  69 label_awal 0.0
Index:  70 label_awal 0.0
Index:  71 label_awal 0.7
Index:  72 label_awal 0.0
Index:  73 label_awal 0.2
Index:  74 label_awal 0.0
Index:  75 label_awal 0.2
Index:  76 label_awal 0.09999999999999998
Index:  77 label_awal 0.0
Index:  78 label_awal 0.0
Index:  79 label_awal 0.2
Index:  80 label_awal -0.1
Index:  81 label_awal 0.0
Index:  82 label_awal -0.5
Index:  83 label_awal 0.0
Index:  84 label_awal 0.14999999999999997
Index:  85 label_awal 0.23047619047619045
Index:  86 label_awal 0.06666666666666667
Index:  87 label_awal -0.2
Index:  88 label_awal 0.0
Index:  89 label_awal -0.30000000000000004
Index:  90 label_awal 0.21666666666666667
Index:  91 label_awal 0.0
Index:  92 label_awal 0.0
Index:  93 label_awal 0.2
Index:  94 label_awal -0.3
Index:  95 label_awal 0.375
Index:  96 label_awal 0.5
Index:  97 label_awal 0.0
Index:  98 label_awal 0.0
Index:  99 label_awal 0.0
Index:  100 label_awal 0.0
Index:  101 label_awal 0.3
Index:  102 label_awal 0.0
Index:  103 label_awal 0.2
Index:  104 label_awal 0.0
Index:  105 label_awal -0.3499999999999999
Index:  106 label_awal -0.1277777777777778
Index:  107 label_awal -0.15555555555555559
Index:  108 label_awal -0.21071428571428572
Index:  109 label_awal 0.0
Index:  110 label_awal 0.0
Index:  111 label_awal -0.5
Index:  112 label_awal 0.0
Index:  113 label_awal 0.0
Index:  114 label_awal 0.1
Index:  115 label_awal 0.0
Index:  116 label_awal 0.0
Index:  117 label_awal 0.275
Index:  118 label_awal 0.2
Index:  119 label_awal 0.2
Index:  120 label_awal 0.0
Index:  121 label_awal 0.0
Index:  122 label_awal 0.0
Index:  123 label_awal 0.0
Index:  124 label_awal 0.037500000000000006
Index:  125 label_awal 0.0
Index:  126 label_awal 0.0
Index:  127 label_awal 0.0
Index:  128 label_awal 0.0
Index:  129 label_awal -0.2
Index:  130 label_awal 0.0
Index:  131 label_awal 0.33333333333333337
Index:  132 label_awal -0.2
Index:  133 label_awal 0.0
Index:  134 label_awal 0.0
Index:  135 label_awal 0.0
Index:  136 label_awal -0.5
Index:  137 label_awal 0.33333333333333337
Index:  138 label_awal 0.0
Index:  139 label_awal 0.0

In [3]:
df.head()

                                     comment_english label_awal
0  ['hello', 'sis',' just ',' tel ',' daro ',' co...  -0.316667
1  ['pay', 'tags', 'mlh', 'disturbing', 'mulu', '...      -0.25
2  ['how', 'forget', 'paswoord', 'name', 'guna', ...        0.0
3  ['hello', 'kak', 'yesterday', 'wifi', 'dislodg...        0.0
4                             ['report', 'disturbs']        0.0

In [4]:
df['label_awal'].value_counts()

 0.000000    65
 0.200000    11
-0.500000     5
 0.450000     3
-0.200000     3
-0.250000     3
 0.500000     2
-0.155556     2
 0.375000     2
 0.100000     2
 0.433333     2
 0.700000     2
 0.333333     2
 0.183333     2
 0.300000     2
-0.136190     1
-0.300000     1
-0.100000     1
 0.150000     1
 0.230476     1
 0.066667     1
 0.216667     1
 0.600000     1
-0.300000     1
-0.350000     1
-0.127778     1
-0.210714     1
 0.275000     1
 0.037500     1
 0.100000     1
 0.068182     1
 0.400000     1
-0.025000     1
 0.300000     1
 0.116667     1
-0.050000     1
-0.027778     1
 0.400000     1
-0.077778     1
 0.425000     1
 0.291667     1
-0.070000     1
-0.750000     1
-0.666667     1
 0.133333     1
-0.150000     1
-0.316667     1
Name: label_awal, dtype: int64

In [5]:
label = []
for index, row in df.iterrows():
    if row['label_awal'] > 0.0:
        label.append("positive")
    else:
        label.append("negative")
df["label"] = label
df = df.drop(columns=['label_awal'])
df.head(2000)

                                       comment_english     label
0    ['hello', 'sis',' just ',' tel ',' daro ',' co...  negative
1    ['pay', 'tags', 'mlh', 'disturbing', 'mulu', '...  negative
2    ['how', 'forget', 'paswoord', 'name', 'guna', ...  negative
3    ['hello', 'kak', 'yesterday', 'wifi', 'dislodg...  negative
4                               ['report', 'disturbs']  negative
..                                                 ...       ...
135  ['service', 'ott', 'disney', 'plus', 'hotstar'...  negative
136  ['admin', 'sorry', 'update', 'application', 'i...  negative
137  ['use', 'indihome', 'net', 'smooth', 'jaya', '...  positive
138                                          of course  negative
139                                          of course  negative

[140 rows x 2 columns]

In [6]:
df['label'].value_counts()

negative    94
positive    46
Name: label, dtype: int64

In [7]:
df.to_excel('labeling_databersih_facebook_indihome_2.xlsx')