In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
import nltk
import string
import re
import openpyxl
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

In [2]:
columns = ["content", "score"]
df = pd.read_excel(r'C:\Users\Hp\TUGAS AKHIR 2\PLAYSTORE_TELKOMSEL\data_mentah\playstore_telkomsel_8.xlsx', usecols=columns)
df.head(2000)

                                                content  score
0     Sekarang telkomsel maling pulsa ya? Kouta saya...      1
1     Kenapa Tiap nomor beda kuota dan harga ya? Jad...      4
2     Di daerah Tanjung Sari Natar Lampung Selatan, ...      1
3     my Telkomsel tambah update tambah jelek, bukan...      1
4     Aplikasi sampah ram gua 6gb internal 128 buka ...      1
...                                                 ...    ...
1920  Mao aktivasi paket tp ga bisa di buka aplikasi...      1
1921  Suprise Deal Unlimited nya adain lagi dong min...      3
1922  Nyedot pulsa kira kira dong! Data udah di mati...      1
1923  Halo udh 2 hari buka aplikasi my telkomsel gak...      3
1924  Saya menggunakan Telkomsel +/- 9 thn dg nomor ...      1

[1925 rows x 2 columns]

In [3]:
df.content.duplicated().sum()

0

In [4]:
df.drop_duplicates(subset="content", keep=False, inplace=True)
df.head(2000)

                                                content  score
0     Sekarang telkomsel maling pulsa ya? Kouta saya...      1
1     Kenapa Tiap nomor beda kuota dan harga ya? Jad...      4
2     Di daerah Tanjung Sari Natar Lampung Selatan, ...      1
3     my Telkomsel tambah update tambah jelek, bukan...      1
4     Aplikasi sampah ram gua 6gb internal 128 buka ...      1
...                                                 ...    ...
1920  Mao aktivasi paket tp ga bisa di buka aplikasi...      1
1921  Suprise Deal Unlimited nya adain lagi dong min...      3
1922  Nyedot pulsa kira kira dong! Data udah di mati...      1
1923  Halo udh 2 hari buka aplikasi my telkomsel gak...      3
1924  Saya menggunakan Telkomsel +/- 9 thn dg nomor ...      1

[1925 rows x 2 columns]

In [5]:
#case folding
df['content'] = df['content'].str.lower()
df.head(2000)

                                                content  score
0     sekarang telkomsel maling pulsa ya? kouta saya...      1
1     kenapa tiap nomor beda kuota dan harga ya? jad...      4
2     di daerah tanjung sari natar lampung selatan, ...      1
3     my telkomsel tambah update tambah jelek, bukan...      1
4     aplikasi sampah ram gua 6gb internal 128 buka ...      1
...                                                 ...    ...
1920  mao aktivasi paket tp ga bisa di buka aplikasi...      1
1921  suprise deal unlimited nya adain lagi dong min...      3
1922  nyedot pulsa kira kira dong! data udah di mati...      1
1923  halo udh 2 hari buka aplikasi my telkomsel gak...      3
1924  saya menggunakan telkomsel +/- 9 thn dg nomor ...      1

[1925 rows x 2 columns]

In [6]:
#cleaning text
import nltk
import string
import re
nltk.download('punkt')

#import word_tokenize & FreqDist from NLTK
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [7]:
#proses cleaning text
def remove_special_tweet(text):
    text = ' '.join(re.sub("([@#][A-Za-z0-9]+)|(\w+:\/\/\S+)", "", str(text)).split())
    text = re.sub(r'[^a-zA-Z0-9]', ' ', str(text))
    text = re.sub(r'\b\w{1,2}\b', ' ', str(text))
    text = re.sub(r'\s\s+',' ',  str(text))
    text = re.sub(r'\d+', ' ', str(text))
    text = re.sub(r'\b[a-zA-Z]\b', ' ', str(text))
    text = re.sub(r'/(?:https?|ftp):\/\/[\n\S]+/g, ''', ' ', str(text))
    text = re.sub(r'(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)', ' ', str(text))
    text = re.sub(r'[0]', r' ', str(text))
    return text
    return df
df['cleaning_content'] = df['content'].apply(remove_special_tweet)
df.head(2000)

,content,score,cleaning_content
0,sekarang telkomsel maling pulsa ya? kouta saya...,1,sekarang telkomsel maling pulsa kouta saya mas...
1,kenapa tiap nomor beda kuota dan harga ya? jad...,4,kenapa tiap nomor beda kuota dan harga jadi su...
2,"di daerah tanjung sari natar lampung selatan, ...",1,daerah tanjung sari natar lampung selatan sin...
3,"my telkomsel tambah update tambah jelek, bukan...",1,telkomsel tambah update tambah jelek bukannya...
4,aplikasi sampah ram gua 6gb internal 128 buka ...,1,aplikasi sampah ram gua gb internal buka ni...
...,...,...,...
1920,mao aktivasi paket tp ga bisa di buka aplikasi...,1,mao aktivasi paket bisa buka aplikasi nya errr...
1921,suprise deal unlimited nya adain lagi dong min...,3,suprise deal unlimited nya adain lagi dong min...
1922,nyedot pulsa kira kira dong! data udah di mati...,1,nyedot pulsa kira kira dong data udah matiin t...
1923,halo udh 2 hari buka aplikasi my telkomsel gak...,3,halo udh hari buka aplikasi telkomsel gak bisa...
1924,saya menggunakan telkomsel +/- 9 thn dg nomor ...,1,saya menggunakan telkomsel thn nomor sama bbrp...

In [8]:
#proses tokenisasi
def tokenisasi(text):
    text = re.split('\W+', str(text))
    return text
    return df
df['tokenisasi'] = df['cleaning_content'].apply(tokenisasi)
df.head(2000)

,content,score,cleaning_content,tokenisasi
0,sekarang telkomsel maling pulsa ya? kouta saya...,1,sekarang telkomsel maling pulsa kouta saya mas...,"[sekarang, telkomsel, maling, pulsa, kouta, sa..."
1,kenapa tiap nomor beda kuota dan harga ya? jad...,4,kenapa tiap nomor beda kuota dan harga jadi su...,"[kenapa, tiap, nomor, beda, kuota, dan, harga,..."
2,"di daerah tanjung sari natar lampung selatan, ...",1,daerah tanjung sari natar lampung selatan sin...,"[, daerah, tanjung, sari, natar, lampung, sela..."
3,"my telkomsel tambah update tambah jelek, bukan...",1,telkomsel tambah update tambah jelek bukannya...,"[, telkomsel, tambah, update, tambah, jelek, b..."
4,aplikasi sampah ram gua 6gb internal 128 buka ...,1,aplikasi sampah ram gua gb internal buka ni...,"[aplikasi, sampah, ram, gua, gb, internal, buk..."
...,...,...,...,...
1920,mao aktivasi paket tp ga bisa di buka aplikasi...,1,mao aktivasi paket bisa buka aplikasi nya errr...,"[mao, aktivasi, paket, bisa, buka, aplikasi, n..."
1921,suprise deal unlimited nya adain lagi dong min...,3,suprise deal unlimited nya adain lagi dong min...,"[suprise, deal, unlimited, nya, adain, lagi, d..."
1922,nyedot pulsa kira kira dong! data udah di mati...,1,nyedot pulsa kira kira dong data udah matiin t...,"[nyedot, pulsa, kira, kira, dong, data, udah, ..."
1923,halo udh 2 hari buka aplikasi my telkomsel gak...,3,halo udh hari buka aplikasi telkomsel gak bisa...,"[halo, udh, hari, buka, aplikasi, telkomsel, g..."
1924,saya menggunakan telkomsel +/- 9 thn dg nomor ...,1,saya menggunakan telkomsel thn nomor sama bbrp...,"[saya, menggunakan, telkomsel, thn, nomor, sam..."

In [9]:
#import nltk stopword
from nltk.corpus import stopwords

#proses stopword
stopword = nltk.corpus.stopwords.words('indonesian')
stopword.extend(["yg", "dg", "rt", "dgn", "ny", "d", 'klo','kalo', 'amp', 'biar', 'bikin', 'bilang','gak', 'ga', 'krn', 'nya', 
                 'nih', 'sih','si', 'tau', 'tdk', 'tuh', 'tai', 'juga', 'utk', 'ya','jd', 'jgn', 'sdh', 'aja', 'n', 't', 'nyg', 'hehe',
                 'pen', 'u', 'nan', 'loh', 'rt', 'kudu', 'mks', 'wkwk', 'an', 'lah', 'dah', 'asu', 'mjb', 'haha',
                 'yah', 'lha', 'lah', 'hihi', 'ih', 'anjir', 'bgt', 'pake', 'anj', 'bgst', 'anjir'])
def remove_stopwords(text):
    text = [word for word in text if word not in stopword]
    return text
    return df
df['stopword'] = df['tokenisasi'].apply(remove_stopwords)
df.head(2000)

,content,score,cleaning_content,tokenisasi,stopword
0,sekarang telkomsel maling pulsa ya? kouta saya...,1,sekarang telkomsel maling pulsa kouta saya mas...,"[sekarang, telkomsel, maling, pulsa, kouta, sa...","[telkomsel, maling, pulsa, kouta, gb, dapet, s..."
1,kenapa tiap nomor beda kuota dan harga ya? jad...,4,kenapa tiap nomor beda kuota dan harga jadi su...,"[kenapa, tiap, nomor, beda, kuota, dan, harga,...","[nomor, beda, kuota, harga, susah, membeli, ku..."
2,"di daerah tanjung sari natar lampung selatan, ...",1,daerah tanjung sari natar lampung selatan sin...,"[, daerah, tanjung, sari, natar, lampung, sela...","[, daerah, tanjung, sari, natar, lampung, sela..."
3,"my telkomsel tambah update tambah jelek, bukan...",1,telkomsel tambah update tambah jelek bukannya...,"[, telkomsel, tambah, update, tambah, jelek, b...","[, telkomsel, update, jelek, bagus, jelek, pin..."
4,aplikasi sampah ram gua 6gb internal 128 buka ...,1,aplikasi sampah ram gua gb internal buka ni...,"[aplikasi, sampah, ram, gua, gb, internal, buk...","[aplikasi, sampah, ram, gua, gb, internal, buk..."
...,...,...,...,...,...
1920,mao aktivasi paket tp ga bisa di buka aplikasi...,1,mao aktivasi paket bisa buka aplikasi nya errr...,"[mao, aktivasi, paket, bisa, buka, aplikasi, n...","[mao, aktivasi, paket, buka, aplikasi, errrooo..."
1921,suprise deal unlimited nya adain lagi dong min...,3,suprise deal unlimited nya adain lagi dong min...,"[suprise, deal, unlimited, nya, adain, lagi, d...","[suprise, deal, unlimited, adain, min, sblm, j..."
1922,nyedot pulsa kira kira dong! data udah di mati...,1,nyedot pulsa kira kira dong data udah matiin t...,"[nyedot, pulsa, kira, kira, dong, data, udah, ...","[nyedot, pulsa, data, udah, matiin, disedot, s..."
1923,halo udh 2 hari buka aplikasi my telkomsel gak...,3,halo udh hari buka aplikasi telkomsel gak bisa...,"[halo, udh, hari, buka, aplikasi, telkomsel, g...","[halo, udh, buka, aplikasi, telkomsel, muter, ..."
1924,saya menggunakan telkomsel +/- 9 thn dg nomor ...,1,saya menggunakan telkomsel thn nomor sama bbrp...,"[saya, menggunakan, telkomsel, thn, nomor, sam...","[telkomsel, thn, nomor, bbrp, update, app, tel..."

In [10]:
Final = df[['stopword','score']]
Final = Final.rename(columns={'stopword':'text_review'})

In [11]:
Final

                                            text_review  score
0     [telkomsel, maling, pulsa, kouta, gb, dapet, s...      1
1     [nomor, beda, kuota, harga, susah, membeli, ku...      4
2     [, daerah, tanjung, sari, natar, lampung, sela...      1
3     [, telkomsel, update, jelek, bagus, jelek, pin...      1
4     [aplikasi, sampah, ram, gua, gb, internal, buk...      1
...                                                 ...    ...
1920  [mao, aktivasi, paket, buka, aplikasi, errrooo...      1
1921  [suprise, deal, unlimited, adain, min, sblm, j...      3
1922  [nyedot, pulsa, data, udah, matiin, disedot, s...      1
1923  [halo, udh, buka, aplikasi, telkomsel, muter, ...      3
1924  [telkomsel, thn, nomor, bbrp, update, app, tel...      1

[1925 rows x 2 columns]

In [12]:
Final.to_excel('databersih_playstore_telkomsel_8.xlsx')