In [1]:
import pandas as pd
from textblob import TextBlob

In [2]:
columns = ["comment_english"]
df = pd.read_excel(r'C:\Users\Hp\TUGAS AKHIR 2\YOUTUBE_INDIHOME\databersih_english_youtube_indihome\databersih_english_youtube_indihome_12.xlsx', usecols=columns)
df.head(2000)

                                       comment_english
0    ['easy', 'easy', 'series', 'competitiveness', ...
1                                ['Turah', 'Turah', "]
2    ['Come on', 'Indihome', 'effort', 'can', 'pict...
3                                         ['know', '']
4        ['Cool', 'three', 'mas', 'mas', 'madura', '']
..                                                 ...
291  ['Minutes', 'Subtitles', 'Write', 'Butterfly',...
292  ['Forgot', 'Subscribe', 'Support', 'Respect', ...
293                                ['Dustin', 'Ohang']
294  ['money', 'production', 'mending', 'stabilin',...
295             ['Series', 'Internet', 'home', 'fast']

[296 rows x 1 columns]

In [3]:
df['comment_english'] = df['comment_english'].str.lower()
df.head(2000)

                                       comment_english
0    ['easy', 'easy', 'series', 'competitiveness', ...
1                                ['turah', 'turah', "]
2    ['come on', 'indihome', 'effort', 'can', 'pict...
3                                         ['know', '']
4        ['cool', 'three', 'mas', 'mas', 'madura', '']
..                                                 ...
291  ['minutes', 'subtitles', 'write', 'butterfly',...
292  ['forgot', 'subscribe', 'support', 'respect', ...
293                                ['dustin', 'ohang']
294  ['money', 'production', 'mending', 'stabilin',...
295             ['series', 'internet', 'home', 'fast']

[296 rows x 1 columns]

In [4]:
df['label_awal'] = ''
for i,x in df.comment_english.iteritems():
    label_awal = TextBlob(x)
    df['label_awal'][i] = label_awal.sentiment.polarity
    print("Index: ", i ,  "label_awal" , label_awal.sentiment.polarity)

Index:  0 label_awal 0.43333333333333335
Index:  1 label_awal 0.0
Index:  2 label_awal 0.0
Index:  3 label_awal 0.0
Index:  4 label_awal 0.35
Index:  5 label_awal 0.4666666666666667
Index:  6 label_awal 0.0
Index:  7 label_awal 0.0
Index:  8 label_awal 0.16666666666666666
Index:  9 label_awal 0.0
Index:  10 label_awal 0.5
Index:  11 label_awal -0.4
Index:  12 label_awal 0.0
Index:  13 label_awal 0.0
Index:  14 label_awal 0.0
Index:  15 label_awal 0.0
Index:  16 label_awal 0.0
Index:  17 label_awal 0.0
Index:  18 label_awal 0.0
Index:  19 label_awal 0.0
Index:  20 label_awal 0.0
Index:  21 label_awal -0.4
Index:  22 label_awal 0.7
Index:  23 label_awal 0.0
Index:  24 label_awal 0.0
Index:  25 label_awal 0.375
Index:  26 label_awal 0.0
Index:  27 label_awal 0.0
Index:  28 label_awal 0.35
Index:  29 label_awal 0.0
Index:  30 label_awal 0.0
Index:  31 label_awal 0.0
Index:  32 label_awal 0.0
Index:  33 label_awal 0.0
Index:  34 label_awal 0.7
Index:  35 label_awal 0.0
Index:  36 label_awal 0.0
Index:  37 label_awal 0.0
Index:  38 label_awal 0.0
Index:  39 label_awal 0.15625
Index:  40 label_awal 0.0
Index:  41 label_awal -0.5
Index:  42 label_awal 0.0
Index:  43 label_awal 0.0
Index:  44 label_awal 0.0
Index:  45 label_awal 0.0
Index:  46 label_awal 0.0
Index:  47 label_awal 0.0
Index:  48 label_awal -0.5
Index:  49 label_awal 0.0
Index:  50 label_awal 0.0
Index:  51 label_awal 0.0
Index:  52 label_awal -0.08499999999999999
Index:  53 label_awal -0.5
Index:  54 label_awal 0.0
Index:  55 label_awal 0.0
Index:  56 label_awal 0.35
Index:  57 label_awal 0.0
Index:  58 label_awal 0.0
Index:  59 label_awal 0.2
Index:  60 label_awal 0.0
Index:  61 label_awal 0.0
Index:  62 label_awal 0.0
Index:  63 label_awal 0.0
Index:  64 label_awal -0.15000000000000002
Index:  65 label_awal 0.0
Index:  66 label_awal -0.17857142857142858
Index:  67 label_awal 0.4
Index:  68 label_awal 0.0
Index:  69 label_awal 0.15000000000000002
Index:  70 label_awal 0.0
Index:  71 label_awal 0.0
Index:  72 label_awal -0.30000000000000004
Index:  73 label_awal 0.0
Index:  74 label_awal 0.0
Index:  75 label_awal 0.0
Index:  76 label_awal 0.0
Index:  77 label_awal 0.35
Index:  78 label_awal 0.0
Index:  79 label_awal 0.0
Index:  80 label_awal 0.2
Index:  81 label_awal 0.0
Index:  82 label_awal 0.0
Index:  83 label_awal 0.0
Index:  84 label_awal 0.0
Index:  85 label_awal 0.0
Index:  86 label_awal 0.0
Index:  87 label_awal 0.0
Index:  88 label_awal 0.0
Index:  89 label_awal 0.0
Index:  90 label_awal 0.0
Index:  91 label_awal 0.0
Index:  92 label_awal 0.0
Index:  93 label_awal 0.0
Index:  94 label_awal 0.05
Index:  95 label_awal 0.0
Index:  96 label_awal 0.0
Index:  97 label_awal 0.0
Index:  98 label_awal 0.0
Index:  99 label_awal -0.30000000000000004
Index:  100 label_awal 0.0
Index:  101 label_awal 0.08333333333333333
Index:  102 label_awal 0.3
Index:  103 label_awal 0.0
Index:  104 label_awal 0.0
Index:  105 label_awal -0.275
Index:  106 label_awal 0.1578231292517007
Index:  107 label_awal 0.0
Index:  108 label_awal 0.0
Index:  109 label_awal -0.1
Index:  110 label_awal 0.0
Index:  111 label_awal 0.7
Index:  112 label_awal 0.0
Index:  113 label_awal 0.275
Index:  114 label_awal 0.38333333333333336
Index:  115 label_awal 0.0
Index:  116 label_awal 0.0
Index:  117 label_awal 0.0
Index:  118 label_awal 0.0
Index:  119 label_awal 0.0
Index:  120 label_awal 0.0
Index:  121 label_awal 0.0
Index:  122 label_awal 0.0
Index:  123 label_awal 0.35
Index:  124 label_awal 0.5
Index:  125 label_awal 0.0
Index:  126 label_awal 0.0
Index:  127 label_awal 0.0
Index:  128 label_awal 0.0
Index:  129 label_awal 0.0
Index:  130 label_awal 0.0
Index:  131 label_awal -0.16666666666666666
Index:  132 label_awal 0.0
Index:  133 label_awal 0.0
Index:  134 label_awal 0.0
Index:  135 label_awal 0.0
Index:  136 label_awal 0.1
Index:  137 label_awal 0.45499999999999996
Index:  138 label_awal 0.55
Index:  139 label_awal 0.0
Index:  140 label_awal 0.0
Index:  141 label_awal 0.0
Index:  142 label_awal 0.2
Index:  143 label_awal 0.0
Index:  144 label_awal 0.0
Index:  145 label_awal 0.0
Index:  146 label_awal 0.0
Index:  147 label_awal 0.0
Index:  148 label_awal 0.7
Index:  149 label_awal 0.0
Index:  150 label_awal 0.0
Index:  151 label_awal 0.0
Index:  152 label_awal 0.0
Index:  153 label_awal 0.0
Index:  154 label_awal 0.0
Index:  155 label_awal 0.35
Index:  156 label_awal 0.0
Index:  157 label_awal 0.0
Index:  158 label_awal 0.0
Index:  159 label_awal 0.375
Index:  160 label_awal 0.0
Index:  161 label_awal 0.0
Index:  162 label_awal 0.0
Index:  163 label_awal 0.0
Index:  164 label_awal 0.0
Index:  165 label_awal -0.8
Index:  166 label_awal 0.0
Index:  167 label_awal 0.375
Index:  168 label_awal 0.0
Index:  169 label_awal 0.0
Index:  170 label_awal 0.0
Index:  171 label_awal -0.65
Index:  172 label_awal 0.08333333333333333
Index:  173 label_awal 0.0
Index:  174 label_awal 0.0
Index:  175 label_awal 0.0
Index:  176 label_awal 0.0
Index:  177 label_awal 0.16666666666666666
Index:  178 label_awal 0.0
Index:  179 label_awal 0.0
Index:  180 label_awal 0.0
Index:  181 label_awal 0.0
Index:  182 label_awal 0.0
Index:  183 label_awal 0.0
Index:  184 label_awal 0.7
Index:  185 label_awal 0.0
Index:  186 label_awal 0.0
Index:  187 label_awal 0.0
Index:  188 label_awal 0.0
Index:  189 label_awal 0.0
Index:  190 label_awal 0.0
Index:  191 label_awal 0.48333333333333334
Index:  192 label_awal 0.0
Index:  193 label_awal -0.016666666666666663
Index:  194 label_awal -0.05
Index:  195 label_awal 0.0
Index:  196 label_awal 0.1
Index:  197 label_awal 0.375
Index:  198 label_awal 0.0
Index:  199 label_awal 0.0
Index:  200 label_awal 0.8
Index:  201 label_awal 0.0
Index:  202 label_awal 0.0
Index:  203 label_awal 0.0
Index:  204 label_awal 0.0
Index:  205 label_awal 0.0
Index:  206 label_awal 0.0
Index:  207 label_awal -0.5
Index:  208 label_awal -0.5
Index:  209 label_awal 0.0
Index:  210 label_awal 0.25
Index:  211 label_awal -0.5
Index:  212 label_awal 0.32499999999999996
Index:  213 label_awal 0.0
Index:  214 label_awal 0.0
Index:  215 label_awal 0.0
Index:  216 label_awal 0.0
Index:  217 label_awal 0.0
Index:  218 label_awal 0.0
Index:  219 label_awal 0.0
Index:  220 label_awal 0.0
Index:  221 label_awal 0.0
Index:  222 label_awal 0.0
Index:  223 label_awal 0.375
Index:  224 label_awal -0.15185185185185185
Index:  225 label_awal -0.5
Index:  226 label_awal -0.5
Index:  227 label_awal 0.0
Index:  228 label_awal -0.25
Index:  229 label_awal 0.24814814814814812
Index:  230 label_awal 0.0
Index:  231 label_awal -0.5
Index:  232 label_awal 0.0
Index:  233 label_awal 0.0
Index:  234 label_awal 0.0
Index:  235 label_awal 1.0
Index:  236 label_awal -0.5
Index:  237 label_awal 0.0
Index:  238 label_awal 0.35
Index:  239 label_awal 0.0
Index:  240 label_awal 0.0
Index:  241 label_awal 0.0
Index:  242 label_awal -0.35
Index:  243 label_awal 0.06666666666666665
Index:  244 label_awal 0.0
Index:  245 label_awal -0.15
Index:  246 label_awal 0.0
Index:  247 label_awal 0.175
Index:  248 label_awal 0.0
Index:  249 label_awal -0.5
Index:  250 label_awal 0.0
Index:  251 label_awal -0.7
Index:  252 label_awal 0.0
Index:  253 label_awal -0.5
Index:  254 label_awal -0.5
Index:  255 label_awal 0.0
Index:  256 label_awal 0.0
Index:  257 label_awal 0.3375
Index:  258 label_awal 1.0
Index:  259 label_awal 0.2333333333333333
Index:  260 label_awal 0.7
Index:  261 label_awal 0.0
Index:  262 label_awal 0.0
Index:  263 label_awal 0.0
Index:  264 label_awal 0.0
Index:  265 label_awal 0.0
Index:  266 label_awal 0.0
Index:  267 label_awal -0.5
Index:  268 label_awal 0.25
Index:  269 label_awal 0.0
Index:  270 label_awal 0.2
Index:  271 label_awal 0.5
Index:  272 label_awal 0.35
Index:  273 label_awal 0.23333333333333334
Index:  274 label_awal 0.0
Index:  275 label_awal 0.0
Index:  276 label_awal 0.0
Index:  277 label_awal 0.5
Index:  278 label_awal 0.0
Index:  279 label_awal 0.375
Index:  280 label_awal -0.1027777777777778
Index:  281 label_awal 0.25
Index:  282 label_awal -0.5
Index:  283 label_awal 0.0
Index:  284 label_awal -0.5
Index:  285 label_awal 0.35
Index:  286 label_awal 0.6
Index:  287 label_awal -0.2
Index:  288 label_awal 0.0
Index:  289 label_awal 0.375
Index:  290 label_awal 0.16666666666666666
Index:  291 label_awal 0.0
Index:  292 label_awal 0.0
Index:  293 label_awal 0.0
Index:  294 label_awal 0.0
Index:  295 label_awal 0.2

In [5]:
df.head()

                                     comment_english label_awal
0  ['easy', 'easy', 'series', 'competitiveness', ...   0.433333
1                              ['turah', 'turah', "]        0.0
2  ['come on', 'indihome', 'effort', 'can', 'pict...        0.0
3                                       ['know', '']        0.0
4      ['cool', 'three', 'mas', 'mas', 'madura', '']       0.35

In [6]:
df['label_awal'].value_counts()

 0.000000    194
-0.500000     16
 0.350000      9
 0.375000      7
 0.700000      6
 0.200000      5
 0.500000      4
 0.166667      3
 0.250000      3
 0.083333      2
-0.300000      2
 0.100000      2
 1.000000      2
-0.400000      2
 0.325000      1
-0.350000      1
-0.151852      1
-0.250000      1
 0.248148      1
 0.800000      1
 0.433333      1
 0.175000      1
 0.066667      1
-0.150000      1
-0.016667      1
-0.700000      1
 0.337500      1
 0.233333      1
 0.233333      1
-0.102778      1
 0.600000      1
-0.050000      1
-0.166667      1
 0.483333      1
-0.650000      1
 0.466667      1
 0.156250      1
-0.085000      1
-0.150000      1
-0.178571      1
 0.400000      1
 0.150000      1
 0.050000      1
 0.300000      1
-0.275000      1
 0.157823      1
-0.100000      1
 0.275000      1
 0.383333      1
 0.455000      1
 0.550000      1
-0.800000      1
-0.200000      1
Name: label_awal, dtype: int64

In [7]:
label = []
for index, row in df.iterrows():
    if row['label_awal'] < 0.0:
        label.append("negative")
    else:
        label.append("positive")
df["label"] = label
df = df.drop(columns=['label_awal'])
df.head(2000)

                                       comment_english     label
0    ['easy', 'easy', 'series', 'competitiveness', ...  positive
1                                ['turah', 'turah', "]  positive
2    ['come on', 'indihome', 'effort', 'can', 'pict...  positive
3                                         ['know', '']  positive
4        ['cool', 'three', 'mas', 'mas', 'madura', '']  positive
..                                                 ...       ...
291  ['minutes', 'subtitles', 'write', 'butterfly',...  positive
292  ['forgot', 'subscribe', 'support', 'respect', ...  positive
293                                ['dustin', 'ohang']  positive
294  ['money', 'production', 'mending', 'stabilin',...  positive
295             ['series', 'internet', 'home', 'fast']  positive

[296 rows x 2 columns]

In [8]:
df['label'].value_counts()

positive    259
negative     37
Name: label, dtype: int64

In [9]:
df.to_excel('labeling_databersih_youtube_indihome_12.xlsx')