In [1]:
import pandas as pd
from textblob import TextBlob

In [2]:
columns = ["comment_english"]
df = pd.read_excel(r'C:\Users\Hp\TUGAS AKHIR 2\INSTAGRAM_INDIHOME\data bersih_translate instagram indihome\databersih_english_instagram_indihome_8.xlsx', usecols=columns)
df['label_awal'] = ''
for i,x in df.comment_english.iteritems():
    label_awal = TextBlob(x)
    df['label_awal'][i] = label_awal.sentiment.polarity
    print("Index: ", i ,  "label_awal" , label_awal.sentiment.polarity)

Index:  0 label_awal 0.0
Index:  1 label_awal 0.0
Index:  2 label_awal 0.0
Index:  3 label_awal -0.6
Index:  4 label_awal 0.0
Index:  5 label_awal 0.0
Index:  6 label_awal 0.0
Index:  7 label_awal 0.0
Index:  8 label_awal 0.0
Index:  9 label_awal 0.0
Index:  10 label_awal 0.0
Index:  11 label_awal 0.2
Index:  12 label_awal 0.0
Index:  13 label_awal 0.0
Index:  14 label_awal -0.09999999999999999
Index:  15 label_awal 0.0
Index:  16 label_awal 0.0
Index:  17 label_awal -0.5
Index:  18 label_awal 0.0
Index:  19 label_awal 0.0
Index:  20 label_awal -0.2
Index:  21 label_awal 0.13636363636363635
Index:  22 label_awal 0.6
Index:  23 label_awal 0.4375
Index:  24 label_awal 0.0
Index:  25 label_awal 0.43333333333333335
Index:  26 label_awal -0.4
Index:  27 label_awal 0.0
Index:  28 label_awal 0.2
Index:  29 label_awal 0.0
Index:  30 label_awal 0.0
Index:  31 label_awal 0.0
Index:  32 label_awal 0.0
Index:  33 label_awal 0.1
Index:  34 label_awal 0.1
Index:  35 label_awal 0.0
Index:  36 label_awal 0.0
Index:  37 label_awal -0.2
Index:  38 label_awal 0.0
Index:  39 label_awal 0.0
Index:  40 label_awal 0.0
Index:  41 label_awal 0.0
Index:  42 label_awal 0.0
Index:  43 label_awal -0.1
Index:  44 label_awal 0.0
Index:  45 label_awal 0.2
Index:  46 label_awal 0.0
Index:  47 label_awal 0.39999999999999997
Index:  48 label_awal 0.0
Index:  49 label_awal 0.5
Index:  50 label_awal 0.6
Index:  51 label_awal 0.0
Index:  52 label_awal -0.3
Index:  53 label_awal 0.0
Index:  54 label_awal 0.0
Index:  55 label_awal -0.17857142857142858
Index:  56 label_awal 0.0
Index:  57 label_awal -0.7
Index:  58 label_awal 0.0
Index:  59 label_awal -0.06666666666666667
Index:  60 label_awal -0.1
Index:  61 label_awal 0.11666666666666665
Index:  62 label_awal 0.0
Index:  63 label_awal -0.19166666666666665
Index:  64 label_awal 0.0
Index:  65 label_awal 0.0
Index:  66 label_awal 0.0
Index:  67 label_awal -0.03333333333333336
Index:  68 label_awal -0.30000000000000004
Index:  69 label_awal 0.1
Index:  70 label_awal -0.5
Index:  71 label_awal 0.0
Index:  72 label_awal 0.0
Index:  73 label_awal 0.0
Index:  74 label_awal 0.0
Index:  75 label_awal -0.5
Index:  76 label_awal -0.5
Index:  77 label_awal 0.0
Index:  78 label_awal 0.02500000000000001
Index:  79 label_awal 0.35
Index:  80 label_awal 0.0
Index:  81 label_awal -0.038095238095238106
Index:  82 label_awal 0.0
Index:  83 label_awal 0.0
Index:  84 label_awal 0.55
Index:  85 label_awal 0.0
Index:  86 label_awal 0.0
Index:  87 label_awal 0.0
Index:  88 label_awal 0.0
Index:  89 label_awal 0.0
Index:  90 label_awal 0.0
Index:  91 label_awal 0.0
Index:  92 label_awal 0.4
Index:  93 label_awal 0.4
Index:  94 label_awal 0.5
Index:  95 label_awal 0.4
Index:  96 label_awal 0.0
Index:  97 label_awal 0.5
Index:  98 label_awal 0.6
Index:  99 label_awal -0.5
Index:  100 label_awal 0.0
Index:  101 label_awal 0.0
Index:  102 label_awal -0.15555555555555559
Index:  103 label_awal 0.1
Index:  104 label_awal 0.0
Index:  105 label_awal 0.0
Index:  106 label_awal 0.0
Index:  107 label_awal 0.0
Index:  108 label_awal 0.0
Index:  109 label_awal 0.5
Index:  110 label_awal 0.0
Index:  111 label_awal 0.0
Index:  112 label_awal 0.0
Index:  113 label_awal 0.0
Index:  114 label_awal 0.5
Index:  115 label_awal 0.0
Index:  116 label_awal -0.4
Index:  117 label_awal -0.2
Index:  118 label_awal 0.0
Index:  119 label_awal 0.0
Index:  120 label_awal -0.17083333333333328
Index:  121 label_awal 0.0
Index:  122 label_awal 0.0
Index:  123 label_awal 0.2
Index:  124 label_awal -0.2875
Index:  125 label_awal 0.0
Index:  126 label_awal 0.25
Index:  127 label_awal 0.0
Index:  128 label_awal -0.5
Index:  129 label_awal 0.0
Index:  130 label_awal 0.0
Index:  131 label_awal 0.0
Index:  132 label_awal 0.0
Index:  133 label_awal 0.0
Index:  134 label_awal -0.16666666666666666
Index:  135 label_awal -0.1
Index:  136 label_awal -0.5
Index:  137 label_awal 0.0
Index:  138 label_awal -0.07142857142857144

In [3]:
df.head()

                                     comment_english label_awal
0             ['mini', 'mantep', 'post', 'benefits']        0.0
1                                      ['check', '']        0.0
2                                        ['', 'pay']        0.0
3  ['afraid', 'data', 'ilang', 'untung', 'mimin',...       -0.6
4                                      ['check', '']        0.0

In [4]:
df['label_awal'].value_counts()

 0.000000    81
-0.500000     7
 0.500000     5
 0.100000     4
 0.200000     4
 0.400000     3
-0.200000     3
 0.600000     3
-0.100000     3
-0.400000     2
-0.033333     1
-0.170833     1
-0.287500     1
-0.155556     1
 0.250000     1
-0.166667     1
 0.550000     1
-0.038095     1
 0.350000     1
 0.025000     1
-0.300000     1
-0.700000     1
-0.191667     1
 0.116667     1
-0.066667     1
-0.600000     1
-0.178571     1
-0.300000     1
 0.400000     1
 0.433333     1
 0.437500     1
 0.136364     1
-0.100000     1
-0.071429     1
Name: label_awal, dtype: int64

In [5]:
label = []
for index, row in df.iterrows():
    if row['label_awal'] > 0.0:
        label.append("positive")
    else:
        label.append("negative")
df["label"] = label
df = df.drop(columns=['label_awal'])
df.head(2000)

                                       comment_english     label
0               ['mini', 'mantep', 'post', 'benefits']  negative
1                                        ['check', '']  negative
2                                          ['', 'pay']  negative
3    ['afraid', 'data', 'ilang', 'untung', 'mimin',...  negative
4                                        ['check', '']  negative
..                                                 ...       ...
134  ['pay', 'late', 'day', 'already', 'dead', 'net...  negative
135               ['net', 'like', 'missing', 'parahh']  negative
136  ['info', 'city', 'used', 'install', 'difficult...  negative
137  ['times', 'report', 'answer', 'nihil', 'patien...  negative
138  ['min', 'pairs',' home ',' difficult ',' right...  negative

[139 rows x 2 columns]

In [6]:
df['label'].value_counts()

negative    111
positive     28
Name: label, dtype: int64

In [7]:
df.to_excel('labeling_databersih_instagram_indihome_8.xlsx')